camunda.bpm:
  auto-deployment-enabled: true
  admin-user:
    id: admin
    password: admin
  filter:
    create: All tasks

spring:
  datasource:
    url: jdbc:postgresql://localhost/blps
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:update